### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by brock** [ncsa/Scheduler#2]
Hey @victor-anisimov 

Would you be alright with changing the README file in this repo to markdown format? It formats the typeface and makes things a little easier to read. I'd be happy to help you out and could even submit a pull request for you if you've never used markdown, as long as that is okay on your end.

**Comment by victor-anisimov** [comment]
Hey Brock. Thanks for the suggestion. Maintaining two copies of README is not very exciting but improving the visual appeal is the right way to go. Will do it soon.

**Comment by brock** [comment]
Thanks for considering it Victor!
